# Generated by Django 4.2.7 on 2023-11-10 11:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_de_campo', models.CharField(max_length=64)),
                ('classe', models.CharField(max_length=64)),
                ('fase', models.CharField(max_length=64)),
                ('tipo_investimento', models.CharField(choices=[('I', 'Implantação'), ('C', 'Crescimento vegetativo'), ('A', 'Ampliação'), ('M', 'Melhorias'), ('R', 'Reposição de Ativos'), ('A/O', 'Administrativo/Operacional')], max_length=3)),
                ('etapa_do_servico', models.CharField(choices=[('M', 'Manancial'), ('C', 'Captação'), ('A', 'Adução'), ('T', 'Tratamento'), ('R', 'Reservação'), ('D', 'Distribuição'), ('C', 'Coleta'), ('R', 'Recalque'), ('N', 'NA')], max_length=64)),
                ('situacao_atual', models.CharField(max_length=64)),
                ('proprietario', models.CharField(max_length=64)),
                ('doacao', models.BooleanField()),
                ('valor_original', models.FloatField()),
                ('vida_util_reg_anos', models.IntegerField()),
                ('vida_util_reg_meses', models.IntegerField()),
                ('data_insercao', models.DateField()),
                ('data_projeto', models.DateField()),
                ('data_obra', models.DateField()),
                ('data_operacao', models.DateField()),
                ('criado_por', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('P/A', 'Projeto em andamento'), ('P/P', 'Projeto paralisado'), ('P/C', 'Projeto cancelado'), ('O/A', 'Obra em andamento'), ('O/P', 'Obra paralisada'), ('O/C', 'Obra cancelada'), ('A/O', 'Ativo em operação'), ('A', 'No almoxarifado'), ('R', 'Ativo reserva'), ('U', 'Ativo fora de uso'), ('D', 'Ativo desativado')], max_length=3)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(default='', max_length=10, unique=True)),
                ('coordenada_x', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('coordenada_y', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.CharField(max_length=50)),
                ('sistemas', models.IntegerField(choices=[('A', 'Água'), ('E', 'Esgoto'), ('A/O', 'Administrativo/Operacional')])),
                ('tipo', models.CharField(choices=[('E', 'Enterrado'), ('V', 'Visivel'), ('O', 'Outro')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='unidades_do_sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('id_localidade', models.IntegerField()),
                ('id_sistemas', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('criado_por', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('telefone', models.CharField(max_length=11)),
                ('funcao', models.CharField(choices=[('P', 'Prestador'), ('R', 'Regulador'), ('U', 'Usuario'), ('A', 'Administrador')], max_length=1)),
                ('criado_em', models.DateField()),
                ('criado_por', models.CharField(max_length=64)),
                ('senha', models.CharField(default='Padronizado', max_length=128)),
            ],
        ),
    ]
