export const AtivosOpColumns = [
    {name: "CÓDIGO", uid: "code"},
    {name: "NOME DE CAMPO", uid: "campName"},
    {name: "CLASSE", uid: "class", sortable: true},
    {name: "DATA DE INSERÇÃO", uid: "insertionDate", sortable: true},
    {name: "DATA DE OBRA", uid: "obraDate", sortable: true},
    {name: "DATA DE OPERAÇÃO", uid: "operationDate", sortable: true},
    {name: "FASE", uid: "phase", sortable: true},
    {name: 'TIPO DE INVESTIMENTO', uid: 'investimentType', sortable: true},
    {name: 'ETAPA DO SERVIÇO', uid: 'serviceStep', sortable: true},
    {name: "SITUAÇÃO ATUAL" , uid: "currentSituation", sortable: true},
    {name: "PROPRIETÁRIO", uid: "owner", sortable: true},
    {name: "VALOR ORIGINAL", uid: "originalValue", sortable: true},
    {name: "DOAÇÃO", uid: "donation", sortable: true},
    {name: "VIDA ÚTIL - MESES", uid: "utilLifeMonths", sortable: true},
    {name: "VIDA ÚTIL - ANOS", uid: "utilLifeYears", sortable: true},
    {name: "STATUS", uid: "status"},
    {name: "CRIADO POR", uid: "createdBy", sortable: true},
    {name: "CRIADO EM", uid: "createdAt", sortable: true},
    {name: "LATITUDE" , uid: "latitude", sortable: true},
    {name: "LONGITUDE", uid: "longitude", sortable: true},
    {name: "LOCALIDADE", uid: "locality", sortable: true},
    {name: "ENDERECO", uid: "address", sortable: true},
    {name: "ACTIONS", uid: "actions", sortable: true}
  ];