export const AtivosOpColumns = [
  {name: "CÓDIGO", uid: "code"},
  {name: "NOME DE CAMPO", uid: "campName"},
  {name: "CLASSE", uid: "class"},
  {name: "DATA DE INSERÇÃO", uid: "insertionDate"},
  {name: "DATA DE OBRA", uid: "obraDate"},
  {name: "DATA DE OPERAÇÃO", uid: "operationDate"},
  {name: "FASE", uid: "phase"},
  {name: 'TIPO DE INVESTIMENTO', uid: 'investimentType',  },
  {name: 'TIPO DE ATIVO', uid: 'activeType'},
  {name: 'ETAPA DO SERVIÇO', uid: 'serviceStep',  },
  {name: "SITUAÇÃO ATUAL" , uid: "currentSituation",  },
  {name: "PROPRIETÁRIO", uid: "owner",  },
  {name: "VALOR ORIGINAL", uid: "originalValue",  },
  {name: "DOAÇÃO", uid: "donation",  },
  {name: "VIDA ÚTIL - MESES", uid: "utilLifeMonths",  },
  {name: "VIDA ÚTIL - ANOS", uid: "utilLifeYears",  },
  {name: "STATUS", uid: "status"},
  {name: "CRIADO POR", uid: "createdBy",  },
  {name: "CRIADO EM", uid: "createdAt",  },
  {name: "LATITUDE" , uid: "latitude",  },
  {name: "LONGITUDE", uid: "longitude",  },
  {name: "LOCALIDADE", uid: "locality",  },
  {name: "ENDERECO", uid: "address",  },
  {name: "ACTIONS", uid: "actions",  }
];

export const ativosAdminColumns = [
  {name: 'TIPO DE ATIVO', uid: 'activeType'},
  {name: 'NOME DO ATIVO', uid: 'name'},
  {name: 'CÓDIGO ATIVO', uid: 'code'},
  {name: 'CLASSE DO ATIVO', uid: 'class'},
  {name: 'PROPRIETÁRIO ATUAL', uid: 'owner'},
  {name: 'DOAÇÃO', uid: 'donation'},
  {name: 'VALOR ORIGINAL', uid: 'originalValue'},
  {name: 'VALOR ATUAL', uid: 'currentValue'},
  {name: 'STATUS', uid: 'status'},
  {name: 'DATA DE INSERCAO', uid: 'insertionDate'},
  {name: 'PREVISÃO DE SUBSTIUIÇÃO', uid: 'substitutionDate'},
  {name: 'UNIDADE RELACIONADA', uid: 'unit'},
  {name: 'CRIADO POR', uid: 'createdBy'},
  {name: 'ADQUIRIDO POR', uid: 'acquiredBy'},
  {name: 'ACTIONS', uid: 'actions'}
]

export const UnidadesColumns = [
  {name: 'SISTEMAS', uid: 'systems'},
  {name: 'TIPO', uid:'type' },
  {name:'LATITUDE' , uid: 'latitude'},
  {name:'LONGITUDE' , uid:'longitude' },
  {name:'MUNICÍPIO' , uid:'município' },
  {name: 'LOCALIDADE', uid:'locality' },
  {name:'ENDERECO' , uid: 'address'},
  {name:'ACTIONS' , uid:'actions' },
]