# Generated by Django 5.0 on 2024-01-02 15:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_alter_usuarios_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos_Administrativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ativo', models.CharField(choices=[('A', 'Automóvel'), ('M', 'Móvel'), ('I', 'Imóvel'), ('E', 'Eletrônico')], default='I', max_length=1)),
                ('nome_ativo', models.CharField(max_length=64)),
                ('código_ativo', models.CharField(max_length=64)),
                ('proprietario', models.CharField(max_length=64)),
                ('doacao', models.BooleanField()),
                ('valor_original', models.FloatField()),
                ('valor_atual', models.FloatField()),
                ('status', models.CharField(choices=[('F', 'Ativo Em Funcionamento'), ('D', 'Ativo Desativado'), ('R', 'Ativo Reservado'), ('P', 'Ativo Paralisado'), ('R', 'Ativo em Reforma/Reparo'), ('C', 'Ativo Cancelado'), ('O', 'Ativo Obsoleto'), ('U', 'Ativo Fora de Uso')], default='F', max_length=3)),
                ('data_insercao', models.DateField()),
                ('previsao_substituicao', models.DateField()),
                ('criado_por', models.CharField(max_length=64)),
                ('adquirido_por', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Ativos_Operacionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_de_campo', models.CharField(max_length=64)),
                ('tipo_ativo', models.CharField(choices=[('V', 'Visivel'), ('E', 'Enterrado')], default='V', max_length=1)),
                ('classe', models.CharField(max_length=64)),
                ('fase', models.CharField(max_length=64)),
                ('tipo_investimento', models.CharField(choices=[('I', 'Implantação'), ('C', 'Crescimento vegetativo'), ('A', 'Ampliação'), ('M', 'Melhorias'), ('R', 'Reposição de Ativos')], max_length=3)),
                ('etapa_do_servico', models.CharField(choices=[('M', 'Manancial'), ('C', 'Captação'), ('A', 'Adução'), ('T', 'Tratamento'), ('R', 'Reservação'), ('D', 'Distribuição'), ('C', 'Coleta'), ('R', 'Recalque'), ('N', 'NA')], max_length=64)),
                ('situacao_atual', models.CharField(max_length=64)),
                ('proprietario', models.CharField(max_length=64)),
                ('doacao', models.BooleanField()),
                ('valor_original', models.FloatField()),
                ('vida_util_reg_anos', models.IntegerField()),
                ('vida_util_reg_meses', models.IntegerField()),
                ('data_insercao', models.DateField()),
                ('data_projeto', models.DateField()),
                ('data_obra', models.DateField()),
                ('data_operacao', models.DateField()),
                ('criado_por', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('P/A', 'Projeto em andamento'), ('P/P', 'Projeto paralisado'), ('P/C', 'Projeto cancelado'), ('O/A', 'Obra em andamento'), ('O/P', 'Obra paralisada'), ('O/C', 'Obra cancelada'), ('A/O', 'Ativo em operação'), ('A', 'No almoxarifado'), ('R', 'Ativo reserva'), ('U', 'Ativo fora de uso'), ('D', 'Ativo desativado')], default='P/A', max_length=3)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(default='', max_length=10, unique=True)),
                ('coordenada_x', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('coordenada_y', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sistemas', models.IntegerField(choices=[('A', 'Administrativo'), ('O', 'operacional(Unidades de tratamento)')], default='Administrativo')),
                ('tipo', models.CharField(choices=[('S', 'Sede'), ('F', 'Filial'), ('TA', 'Tratamento de Água'), ('TE', 'Tratamento de Esgoto'), ('TB', 'Tratamento de Agua e Esgoto')], default='Filial', max_length=2)),
                ('coordenada_x', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('coordenada_y', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('localidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Ativos',
        ),
        migrations.DeleteModel(
            name='Localidades',
        ),
        migrations.DeleteModel(
            name='unidades_do_sistema',
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.unidades'),
        ),
        migrations.AddField(
            model_name='ativos_administrativos',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.unidades'),
        ),
    ]
