# Generated by Django 5.0 on 2024-01-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_ativos_administrativos_ativos_operacionais_unidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='sistemas',
            field=models.CharField(choices=[('A', 'Administrativo'), ('O', 'operacional(Unidades de tratamento)')], default='Administrativo'),
        ),
    ]
