# Generated by Django 5.0 on 2024-01-04 13:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_rename_coordenada_x_unidades_coordenada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidades',
            name='coordenada',
        ),
        migrations.AddField(
            model_name='unidades',
            name='latitude',
            field=models.FloatField(default=0.0, help_text='Latitude', verbose_name='Outlet Latitude'),
        ),
        migrations.AddField(
            model_name='unidades',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Point(longitude, latitude)', null=True, srid=4326, verbose_name='Localizado no Mapa'),
        ),
        migrations.AddField(
            model_name='unidades',
            name='longitude',
            field=models.FloatField(default=0.0, help_text='Longitude', verbose_name='Outlet Longitude'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='data/images/'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='localidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
