# Generated by Django 5.0 on 2024-01-04 13:22

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_remove_unidades_coordenada_unidades_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='imageUrl',
        ),
        migrations.AlterField(
            model_name='unidades',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), geography=True, help_text='Point(longitude, latitude)', null=True, srid=4326, verbose_name='Outlet'),
        ),
    ]
