# Generated by Django 5.0 on 2024-01-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_remove_ativos_operacionais_coordenada_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativos_administrativos',
            name='valor_atual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ativos_administrativos',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ativos_operacionais',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
