# Generated by Django 5.0 on 2024-01-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_alter_ativos_administrativos_valor_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
