# Generated by Django 5.0 on 2024-01-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_alter_usuarios_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
