# Generated by Django 5.0 on 2024-01-08 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_filtros'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltrosAtivosAdministrativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo_administrativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.ativos_administrativos')),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.filtros')),
            ],
        ),
        migrations.AddField(
            model_name='filtros',
            name='ativos_administrativos',
            field=models.ManyToManyField(related_name='filtros_ativos_administrativos', through='world.FiltrosAtivosAdministrativos', to='world.ativos_administrativos'),
        ),
        migrations.CreateModel(
            name='FiltrosAtivosOperacionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo_operacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.ativos_operacionais')),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.filtros')),
            ],
        ),
        migrations.AddField(
            model_name='filtros',
            name='ativos_operacionais',
            field=models.ManyToManyField(related_name='filtros_ativos_operacionais', through='world.FiltrosAtivosOperacionais', to='world.ativos_operacionais'),
        ),
        migrations.CreateModel(
            name='FiltrosUnidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.filtros')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.unidades')),
            ],
        ),
        migrations.AddField(
            model_name='filtros',
            name='unidades',
            field=models.ManyToManyField(related_name='filtros_unidades', through='world.FiltrosUnidades', to='world.unidades'),
        ),
        migrations.CreateModel(
            name='FiltrosUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.filtros')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='filtros',
            name='usuarios',
            field=models.ManyToManyField(related_name='filtros_usuarios', through='world.FiltrosUsuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
