# Generated by Django 5.0 on 2024-01-08 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0014_filtrosativosadministrativos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtros',
            name='ativos_administrativos',
        ),
        migrations.RemoveField(
            model_name='filtrosativosoperacionais',
            name='ativo_operacional',
        ),
        migrations.RemoveField(
            model_name='filtrosativosoperacionais',
            name='filtro',
        ),
        migrations.RemoveField(
            model_name='filtros',
            name='ativos_operacionais',
        ),
        migrations.RemoveField(
            model_name='filtrosunidades',
            name='filtro',
        ),
        migrations.RemoveField(
            model_name='filtrosunidades',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='filtros',
            name='unidades',
        ),
        migrations.RemoveField(
            model_name='filtrosusuarios',
            name='filtro',
        ),
        migrations.RemoveField(
            model_name='filtrosusuarios',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='filtros',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='ativos_administrativos',
            name='classe_ativo',
            field=models.CharField(choices=[('P', 'Pessoal'), ('C', 'Computador'), ('I', 'Impressora'), ('V', 'Veículo'), ('E', 'Eletrodomestico'), ('G', 'Geral')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='filtros',
            name='ativos_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.ativos_administrativos'),
        ),
        migrations.AddField(
            model_name='filtros',
            name='ativos_op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.ativos_operacionais'),
        ),
        migrations.AddField(
            model_name='filtros',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.unidades'),
        ),
        migrations.AddField(
            model_name='filtros',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FiltrosAtivosAdministrativos',
        ),
        migrations.DeleteModel(
            name='FiltrosAtivosOperacionais',
        ),
        migrations.DeleteModel(
            name='FiltrosUnidades',
        ),
        migrations.DeleteModel(
            name='FiltrosUsuarios',
        ),
    ]
