# Generated by Django 5.0 on 2024-01-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0015_remove_filtros_ativos_administrativos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filtros',
        ),
    ]
