# Generated by Django 5.0.1 on 2024-01-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0016_delete_filtros'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos_operacionais',
            name='Endereco',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='Município',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='localidade',
            field=models.CharField(blank=True, help_text='Distrito/Localidade', max_length=100, null=True, verbose_name='Sede Municipal'),
        ),
        migrations.AddField(
            model_name='unidades',
            name='Endereco',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='unidades',
            name='Município',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='localidade',
            field=models.CharField(blank=True, help_text='Distrito/Localidade', max_length=100, null=True, verbose_name='Sede Municipal'),
        ),
    ]
