# Generated by Django 5.0 on 2024-01-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0017_ativos_operacionais_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
