# Generated by Django 5.0 on 2024-03-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0020_ativos_operacionais_diâmetro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='código',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='unidades',
            name='data_operacao',
            field=models.DateField(blank=True, help_text='Data de Início da Operação', null=True),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='sistemas',
            field=models.CharField(choices=[('A', 'Administrativo'), ('O', 'operacional')], default='Administrativo'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='tipo',
            field=models.CharField(choices=[('AS', 'Sede Administrativa'), ('AF', 'Filial Administrativa'), ('ETA', 'Estação de Tratamento de Água'), ('ETE', 'Estação de Tratamento de Esgoto'), ('BGE', 'Barragem')], default='Filial', max_length=3),
        ),
    ]
