# Generated by Django 5.0 on 2024-03-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0021_unidades_código_unidades_data_operacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativos_administrativos',
            name='previsao_substituicao',
        ),
        migrations.RemoveField(
            model_name='ativos_operacionais',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='ativos_operacionais',
            name='doacao',
        ),
        migrations.AddField(
            model_name='ativos_administrativos',
            name='data_operacao',
            field=models.DateField(blank=True, help_text='Data de Entrada em Uso do Item', null=True),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='capacidade_potencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Apenas para conjunto motobomba', max_digits=4, null=True, verbose_name='Capacidade de Potência(cv)'),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='capacidade_vazao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Apenas para conjunto motobomba', max_digits=4, null=True, verbose_name='Capacidade de vazão(l/s)'),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='classe_ativo',
            field=models.CharField(choices=[('BDA', 'Bomba De Agua'), ('E', 'Equipamento'), ('ME', 'Motor Elétrico'), ('RDA', 'Rede de distribuição de Água'), ('RDE', 'Rede Coletora de Esgoto'), ('O', 'Outros')], default='O', max_length=3),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='classificacao_regulatoria',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='conj_motobomba',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='desc_complementar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='especie',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='estado_conservacao',
            field=models.CharField(choices=[('N', 'Novo'), ('B', 'Bom'), ('R', 'Regular'), ('N/R', 'Necessita de Reparos'), ('D', 'Desgastado'), ('I', 'Inutilizável'), ('N/A', 'Não se Aplica')], default='N/A', max_length=3),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='indenizavel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='material',
            field=models.CharField(choices=[('A', 'Aço'), ('C/C', 'Cerâmica e Cimento'), ('CO', 'Concreto'), ('D', 'Defofo'), ('F', 'Ferro'), ('FFU', 'Ferro Fundido'), ('F/P', 'Ferro/PVC'), ('FB', 'Fibra'), ('MC', 'Malha Cerâmica'), ('O', 'Ocre'), ('P', 'PBA'), ('N/A', 'Não se Aplica')], default='N/A', max_length=3),
        ),
        migrations.AddField(
            model_name='ativos_operacionais',
            name='subunidade',
            field=models.CharField(choices=[('C/A', 'Caixa de Areia'), ('C/Q', 'Caixa de Química'), ('C', 'Coagulador'), ('D', 'Decantador'), ('DP', 'Depósito'), ('F/B', 'Filtro Biológico'), ('F/R', 'Filtro Rápido'), ('G', 'Grade'), ('L', 'Laboratório'), ('L/S', 'Leito de secagem'), ('M/V', 'Medidor de Vazão'), ('RU', 'Reator UASB'), ('T/C', 'Tanque de Contato'), ('N/A', 'Não se aplica')], default='N/A', max_length=3),
        ),
        migrations.AddField(
            model_name='unidades',
            name='capacidade_volume',
            field=models.IntegerField(blank=True, help_text='Capacidade de Volumes (m3)', null=True),
        ),
        migrations.AddField(
            model_name='unidades',
            name='classe_unidade',
            field=models.CharField(choices=[('E/E/IC', 'Edificação, Estrutura e Instalações Civis'), ('T', 'Terreno')], default='E/E/IC', max_length=8),
        ),
        migrations.AddField(
            model_name='unidades',
            name='etapa_sistemas',
            field=models.CharField(choices=[('C', 'Captação'), ('CO', 'Coleta'), ('D', 'Distribuição'), ('R', 'Reservação'), ('T', 'Tratamento'), ('N/A', 'Não se Aplica')], default='N/A', max_length=3),
        ),
        migrations.AlterField(
            model_name='ativos_administrativos',
            name='classe_ativo',
            field=models.CharField(choices=[('P', 'Pessoal'), ('C', 'Computador'), ('I', 'Impressora'), ('VM', 'Veículo Motorizado'), ('VP', 'Veículo Manual'), ('E', 'Eletrodoméstico'), ('G', 'Geral'), ('N/A', 'Não se aplica')], default='G', max_length=3),
        ),
        migrations.AlterField(
            model_name='ativos_administrativos',
            name='data_insercao',
            field=models.DateField(blank=True, help_text='Data de Cadastro do Item', null=True),
        ),
        migrations.AlterField(
            model_name='ativos_operacionais',
            name='nome_de_campo',
            field=models.CharField(help_text='Nome das partes', max_length=64),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='tipo',
            field=models.CharField(choices=[('AS', 'Sede Administrativa'), ('AF', 'Filial Administrativa'), ('EAB', 'Estação Elevatória de Água Bruta'), ('EEE', 'Estação Elevatória de Esgoto'), ('ETA', 'Estação de Tratamento de Água'), ('ETE', 'Estação de Tratamento de Esgoto'), ('BGE', 'Barragem')], default='Filial Administrativa', max_length=3),
        ),
    ]
