# Generated by Django 5.0 on 2024-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0022_remove_ativos_administrativos_previsao_substituicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativos_operacionais',
            name='origem',
            field=models.CharField(choices=[('P', 'Próprio'), ('T', 'Terceiro(s)'), ('D', 'Doação')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='ativos_operacionais',
            name='etapa_do_servico',
            field=models.CharField(choices=[('M', 'Manancial'), ('C', 'Captação'), ('A', 'Adução'), ('T', 'Tratamento'), ('R', 'Reservação'), ('D', 'Distribuição'), ('C', 'Coleta'), ('R', 'Recalque'), ('N', 'NA')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='ativos_operacionais',
            name='tipo_investimento',
            field=models.CharField(choices=[('I', 'Implantação'), ('C', 'Crescimento vegetativo'), ('A', 'Ampliação'), ('M', 'Melhorias'), ('R', 'Reposição de Ativos')], default='I', max_length=3),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='classe_unidade',
            field=models.CharField(choices=[('E/E/IC', 'Edificação, Estrutura e Instalações Civis'), ('T', 'Terreno')], default='Edificação, Estrutura e Instalações Civis', max_length=10),
        ),
    ]
