# Generated by Django 5.0 on 2024-03-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0023_ativos_operacionais_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='classe_unidade',
            field=models.CharField(choices=[('E/E/IC', 'Edificação, Estrutura e Instalações Civis'), ('T', 'Terreno')], default='E/E/IC', max_length=10),
        ),
    ]
