# Generated by Django 5.0 on 2024-03-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0024_alter_unidades_classe_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('variacao', models.DecimalField(decimal_places=2, max_digits=3)),
                ('variacao_centesimal', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('num_indice_IBGE', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentagem_variacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variacao_retroativa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('num_indice_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
