# Generated by Django 5.0 on 2024-03-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0025_ipca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipca',
            name='variacao',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
