# Generated by Django 5.0.1 on 2024-03-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0026_alter_ipca_variacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipca',
            name='porcentagem_variacao',
        ),
    ]
