# Generated by Django 5.0 on 2024-03-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0027_remove_ipca_porcentagem_variacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipca',
            name='variacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
