# Generated by Django 5.0 on 2024-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_alter_ipca_variacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipca',
            name='mes_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
