# Generated by Django 5.0 on 2024-03-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0030_ipca_porcentagem_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipca',
            name='num_indice_calculado',
        ),
        migrations.RemoveField(
            model_name='ipca',
            name='variacao_retroativa',
        ),
    ]
